# Starting of with the shared elements through the example:
# User josefauerAS already exists
# User Demo Engineer
# User Java Engineer 1
# User Java Engineer 2
# User Java Engineer 3
# User Infra Engineer 1
# User Infra Engineer 2
# User Infra Engineer 3
# Team Java-Demo
# Team Infra-Demo
# System Demo
#

# Users
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: java-engineer-1
spec:
  profile:
    displayName: Java One
    email: java.one@demo.com
  memberOf:
    - "java-demo-team"
    - "employees"
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: java-engineer-2
spec:
  profile:
    displayName: Java Two
    email: java.two@demo.com
  memberOf:
    - "java-demo-team"
    - "employees"
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: java-engineer-3
spec:
  profile:
    displayName: Java Three
    email: java.three@demo.com
  memberOf:
    - "java-demo-team"
    - "employees"
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: infra-engineer-1
spec:
  profile:
    displayName: Infra One
    email: infra.one@demo.com
  memberOf:
    - "infra-demo-team"
    - "employees"
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: infra-engineer-2
spec:
  profile:
    displayName: Infra Two
    email: infra.two@demo.com
  memberOf:
    - "infra-demo-team"
    - "employees"
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: infra-engineer-3
spec:
  profile:
    displayName: Infra Three
    email: infra.three@demo.com
  memberOf:
    - "infra-demo-team"
    - "employees"
---
# Teams

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infra-demo-team
  description: Demo for a potential Infra team
spec:
  type: team
  profile:
    displayName: Infra Demo Team
    email: infra-admin@demo.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: java-demo-team
  description: Demo for a potential Java team
spec:
  type: team
  profile:
    displayName: Java Demo Team
    email: java-admin@demo.com
  children: []
---
# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo
  description: Demo for all of this
spec:
  owner: java-demo-team
  domain: demo-domain

###
###
# Services, Components, APIs
###
###

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-java
  description: Java Demo Service
  title: Java Demo
  annotations:
    github.com/project-slug: josefauerAS/demo-backstage
    backstage.io/techdocs-ref: dir:.
  # tags have a bit of a strange pattern.
  # They need to be all lower case, seperated by - and are at most 63 characters long.
  # Don't write Java or SpringBoot
  # It has to be java and springboot
  tags:
    - "java"
    - "springboot"
  links:
    - url: https://openjdk.org/
      title: Open JDK because who likes Oracle?
      icon: document
spec:
  owner: java-demo-team
  type: service
  lifecycle: experimental
  system: demo
  providesApis:
    - java-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: java-api
  description: Demo API Java
spec:
  type: openapi
  lifecycle: experimental
  owner: java-demo-team
  system: demo
  definition:
    $text: https://github.com/josefauerAS/demo-backstage/blob/main/docs/openapi/petstore.yaml
